[DATA]
# List of target tickers (comma-separated)
TICKERS = SWTSX, FSDAX, RYOCX
LIVE_DATA_DAYS = 7

[EXECUTION]
ACTIVATION_TIME = 12:00
DECISION_THRESHOLD = 0.65
DEFAULT_INVESTMENT = 100
URL_TOPIC_NAME = penny_investment_manager_12345